heat_template_version: 2017-02-24
 
description: wordpress HPCC


parameters:
  key_name:
    type: string
    description: Name of a key pair to enable SSH access to instances.
    default: hpcc-admin
  flavor:
    type: string
    description: Flavor to use for the WordPress server.
    constraints:
      - custom_constraint: nova.flavor
  image:
    type: string
    description: qcow2
    default: Fedora-Cloud-Base-27-1.6.x86_64
  db_name:
    type: string
    description: WordPress database name
    default: wordpress
    constraints:
      - length: { min: 1, max: 64 }
        description: db_name must be between 1 and 64 characters
      - allowed_pattern: '[a-zA-Z][a-zA-Z0-9]*'
        description: >
          db_name must begin with a letter and contain only alphanumeric
          characters
  db_username:
    type: string
    description: The WordPress database admin account username
    default: admin
    hidden: true
    constraints:
      - length: { min: 1, max: 16 }
        description: db_username must be between 1 and 64 characters
      - allowed_pattern: '[a-zA-Z][a-zA-Z0-9]*'
        description: >
          db_username must begin with a letter and contain only alphanumeric
          characters
resources:
  wordpress_config:
    type: OS::Heat::SoftwareConfig
    properties:
      inputs:
        - name: db_name
        - name: db_user
        - name: db_password
        - name: db_ipaddr
      group: script
      config: { get_file: "https://raw.githubusercontent.com/vusonhust/heat-template/master/wordpress/wp_install.sh"}
 
  db_config:
    type: OS::Heat::SoftwareConfig
    properties:
      inputs:
        - name: db_rootpassword
        - name: db_name
        - name: db_user
        - name: db_password
      group: script
      config: { get_file: "https://raw.githubusercontent.com/vusonhust/heat-template/master/wordpress/db_install.sh"}
 
  db_root_password:
    type: OS::Heat::RandomString
 
  db_password:
    type: OS::Heat::RandomString
 
  wordpress_deployment:
    type: OS::Heat::SoftwareDeployment
    depends_on: db_deployment
    properties:
      config:
        get_resource: wordpress_config
      server:
        get_resource: webserver_instance
      input_values:
        db_name: { get_param: db_name }
        db_user: { get_param: db_username }
        db_password: { get_attr: [ db_password, value ] }
        db_ipaddr: { get_attr: [ dbserver_instance, networks, private, 0 ] }
 
  db_deployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      config:
        get_resource: db_config
      server:
        get_resource: dbserver_instance
      input_values:
        db_rootpassword: { get_attr: [ db_root_password, value ] }
        db_name: { get_param: db_name }
        db_user: { get_param: db_username }
        db_password: { get_attr: [ db_password, value ] }
 
  webserver_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      user_data_format: SOFTWARE_CONFIG
      networks:
        - network: provider
 
  dbserver_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      user_data_format: SOFTWARE_CONFIG
      networks:
        - network: provider
 
outputs:
  WebsiteURL:
    description: URL for Wordpress wiki
    value:
      str_replace:
        template: http://host/wordpress
        params:
          host: { get_attr: [webserver_instance, networks, private, 0] }